### ISSUE TITLE
Issue with python 3.12

### ISSUE THREAD

**Issue by PhilippeR** [cd-athena/EVCA#4]
Is there a recommended version of python to use EVCA ? 

With fresh install of python3.12, I've this error

python3.12 main.py -i short.yuv -r 1920x1080 -c video_name.csv
Importing libraries...
Libraries imported successfully.

Traceback (most recent call last):
  File "/home/ubuntu/github_projects/EVCA/main.py", line 98, in <module>
    main()
  File "/home/ubuntu/github_projects/EVCA/main.py", line 73, in main
    from libs.EVCA import EVCA
  File "/home/ubuntu/github_projects/EVCA/libs/EVCA.py", line 8, in <module>
    from pytorch_wavelets import DWTForward
  File "/home/ubuntu/github_projects/EVCA/env/lib/python3.12/site-packages/pytorch_wavelets/__init__.py", line 22, in <module>
    from pytorch_wavelets.dtcwt.transform2d import DTCWTForward, DTCWTInverse
  File "/home/ubuntu/github_projects/EVCA/env/lib/python3.12/site-packages/pytorch_wavelets/dtcwt/transform2d.py", line 5, in <module>
    from pytorch_wavelets.dtcwt.coeffs import qshift as _qshift, biort as _biort, level1
  File "/home/ubuntu/github_projects/EVCA/env/lib/python3.12/site-packages/pytorch_wavelets/dtcwt/coeffs.py", line 7, in <module>
    from pkg_resources import resource_stream
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by PhilippeR** [comment]
Works with Python3.10
